//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface IBookingApiClient {

    /**
     * @return Success
     */
    bookingAll(): Promise<HotelModel[]>;

    /**
     * @param body (optional) 
     * @return Success
     */
    booking(body: AddBookingModel | undefined): Promise<BookingModel>;
}

export class BookingApiClient implements IBookingApiClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return Success
     */
    bookingAll(): Promise<HotelModel[]> {
        let url_ = this.baseUrl + "/api/booking";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBookingAll(_response);
        });
    }

    protected processBookingAll(response: Response): Promise<HotelModel[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as HotelModel[];
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<HotelModel[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Success
     */
    booking(body: AddBookingModel | undefined): Promise<BookingModel> {
        let url_ = this.baseUrl + "/api/booking";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processBooking(_response);
        });
    }

    protected processBooking(response: Response): Promise<BookingModel> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            result200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver) as BookingModel;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<BookingModel>(null as any);
    }
}

export interface AddBookingModel {
    roomId?: string;
    clientId?: string;
    checkInDate?: string;
    checkOutDate?: string;
}

export interface BookingModel {
    id?: string;
    status?: BookingStatus;
    totalPrice?: number;
    createdAt?: string;
    checkInDate?: string;
    checkOutDate?: string;
    room?: RoomModel;
    client?: ClientModel;
}

export enum BookingStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
}

export interface ClientModel {
    fullName?: string | undefined;
    email?: string | undefined;
}

export interface HotelModel {
    id?: string;
    name?: string | undefined;
    address?: string | undefined;
    country?: string | undefined;
    rooms?: RoomModel[] | undefined;
}

export interface RoomModel {
    id?: string;
    number?: number;
    price?: number;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}